-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2019-08-23 15:03:45 CEST
--   site:      SQL Server 2012
--   type:      SQL Server 2012



CREATE TABLE kandydat (
    idkandydata     bigint IDENTITY NOT NULL,
    zaakceptowany   bit,
    dataaplikacji   datetime,
    osoba           bigint NOT NULL,
    ogloszenie      bigint NOT NULL
);

ALTER TABLE Kandydat ADD constraint kandydat_pk PRIMARY KEY CLUSTERED (IdKandydata)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

CREATE TABLE klient (
    idklienta     bigint IDENTITY NOT NULL,
    nazwafirmy    VARCHAR(100),
    nip           VARCHAR(11),
    wlasciciel    VARCHAR(100),
    telefon       VARCHAR(20),
    miasto        VARCHAR(50),
    dzialalnosc   bigint
);

ALTER TABLE Klient ADD constraint ogloszeniepracownicze_pkv2 PRIMARY KEY CLUSTERED (IdKlienta)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

CREATE TABLE lubi (
    idlubi                   bigint IDENTITY PRIMARY KEY,
    odkiedy                  datetime2,
    stopienzainteresowania   NUMERIC(2),
    osoba                    bigint NOT NULL,
    zainteresowanie          bigint NOT NULL,
);


CREATE TABLE ogloszeniepracownicze (
    idogloszenia    bigint IDENTITY PRIMARY KEY,
    opis            VARCHAR(255),
    zarobki         bigint,
    zleceniodawca   bigint NOT NULL
);



CREATE TABLE ogloszeniezainteresowanie (
    idogloszeniezainteresowanie   bigint IDENTITY NOT NULL,
    zainteresowanie               bigint NOT NULL,
    ogloszenie                    bigint NOT NULL
);



ALTER TABLE ogloszeniezainteresowanie ADD constraint ogloszeniezainteresowanie_pk PRIMARY KEY CLUSTERED (idogloszeniezainteresowanie)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

CREATE TABLE osoba (
    id         bigint IDENTITY NOT NULL,
    imie       VARCHAR(50),
    nazwisko   VARCHAR(50),
    pesel      VARCHAR(11),
    plec       CHAR,
    email      VARCHAR(100),
    telefon    VARCHAR(20)
);



ALTER TABLE osoba ADD constraint osoba_pk PRIMARY KEY CLUSTERED (id)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

CREATE TABLE zainteresowanie (
    idzainteresowania   bigint IDENTITY NOT NULL,
    nazwa               VARCHAR(100)
);



ALTER TABLE zainteresowanie ADD constraint zainteresowanie_pk PRIMARY KEY CLUSTERED (idzainteresowania)
     WITH (
     ALLOW_PAGE_LOCKS = ON , 
     ALLOW_ROW_LOCKS = ON );

CREATE TABLE znajomi (
    idznajomi   bigint IDENTITY PRIMARY KEY,
    znajomy1    bigint NOT NULL,
    znajomy2    bigint NOT NULL
);



ALTER TABLE klient
    ADD CONSTRAINT dzialanosc FOREIGN KEY ( dzialalnosc )
        REFERENCES osoba ( id )
ON DELETE NO ACTION 
    ON UPDATE no action;

ALTER TABLE kandydat
    ADD CONSTRAINT kandydatdoogloszenia FOREIGN KEY ( ogloszenie )
        REFERENCES ogloszeniepracownicze ( idogloszenia )
ON DELETE NO ACTION 
    ON UPDATE no action;

ALTER TABLE lubi
    ADD CONSTRAINT lubi_zainteresowanie_fk FOREIGN KEY ( zainteresowanie )
        REFERENCES zainteresowanie ( idzainteresowania )
ON DELETE NO ACTION 
    ON UPDATE no action;

ALTER TABLE ogloszeniezainteresowanie
    ADD CONSTRAINT ogloszeniezainteresowanie_ogloszeniepracownicze_fk FOREIGN KEY ( ogloszenie )
        REFERENCES ogloszeniepracownicze ( idogloszenia )
ON DELETE NO ACTION 
    ON UPDATE no action;

ALTER TABLE ogloszeniezainteresowanie
    ADD CONSTRAINT ogloszeniezainteresowanie_zainteresowanie_fk FOREIGN KEY ( zainteresowanie )
        REFERENCES zainteresowanie ( idzainteresowania )
ON DELETE NO ACTION 
    ON UPDATE no action;

ALTER TABLE kandydat
    ADD CONSTRAINT osobakandydat FOREIGN KEY ( osoba )
        REFERENCES osoba ( id )
ON DELETE NO ACTION 
    ON UPDATE no action;

ALTER TABLE lubi
    ADD CONSTRAINT osobalubi FOREIGN KEY ( osoba )
        REFERENCES osoba ( id )
ON DELETE NO ACTION 
    ON UPDATE no action;

ALTER TABLE ogloszeniepracownicze
    ADD CONSTRAINT zleceniodawca FOREIGN KEY ( zleceniodawca )
        REFERENCES klient ( idklienta )
ON DELETE NO ACTION 
    ON UPDATE no action;

ALTER TABLE znajomi
    ADD CONSTRAINT znajomy1 FOREIGN KEY ( znajomy1 )
        REFERENCES osoba ( id )
ON DELETE NO ACTION 
    ON UPDATE no action;

ALTER TABLE znajomi
    ADD CONSTRAINT znajomy2v2 FOREIGN KEY ( znajomy2 )
        REFERENCES osoba ( id )
ON DELETE NO ACTION 
    ON UPDATE no action;
	
ALTER TABLE klient 
	ADD CONSTRAINT nipunique UNIQUE (nip);
	
ALTER TABLE osoba 
	ADD CONSTRAINT peselunique UNIQUE (pesel);